language: node_js
node_js:
  - "10.16"

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - npm run solium
  - npm run test

before_deploy:
  - touch .env

deploy:
  provider: script
  skip_cleanup: true
  script: make deploy-ropsten
  on:
    branch: master
    tags: true
