language: node_js
node_js:
  - "10.16"

cache:
  directories:
  - node_modules

install:
  - npm install

script:
  - make test

before_deploy:
  - touch .env

deploy:
  provider: script
  skip_cleanup: true
  script: make deploy-ropsten
  on:
    branch: master
    tags: true

after_deploy:
  - make github-deployment
  - make verify-ropsten